# -------------------------------------------------
# Project created by QtCreator 2013-08-25T15:02:15
# -------------------------------------------------
QT += opengl
TARGET = graphal
TEMPLATE = app
SOURCES += ../libgraphal/visualizationconnector.cpp \
	../libgraphal/valuevertex.cpp \
	../libgraphal/valuestruct.cpp \
	../libgraphal/valuestring.cpp \
	../libgraphal/valueset.cpp \
	../libgraphal/valuereference.cpp \
	../libgraphal/valuenull.cpp \
	../libgraphal/valueint.cpp \
	../libgraphal/valueidentifier.cpp \
	../libgraphal/valuegraph.cpp \
	../libgraphal/valuefloat.cpp \
	../libgraphal/valueedge.cpp \
	../libgraphal/valuebool.cpp \
	../libgraphal/valuearray.cpp \
	../libgraphal/value.cpp \
	../libgraphal/tests.cpp \
	../libgraphal/stringtable.cpp \
	../libgraphal/objectfactory.cpp \
	../libgraphal/objectcreator.cpp \
	../libgraphal/nodevalue.cpp \
	../libgraphal/nodeunary.cpp \
	../libgraphal/nodeposition.cpp \
	../libgraphal/nodeloop.cpp \
	../libgraphal/nodejumpcontinue.cpp \
	../libgraphal/nodejumpbreak.cpp \
	../libgraphal/nodeglobal.cpp \
	../libgraphal/nodefunctionscript.cpp \
	../libgraphal/nodefunctioncall.cpp \
	../libgraphal/nodefunctionbuiltin.cpp \
	../libgraphal/nodefunction.cpp \
	../libgraphal/nodeforeach.cpp \
	../libgraphal/nodeemptycommand.cpp \
	../libgraphal/nodecondition.cpp \
	../libgraphal/nodeblock.cpp \
	../libgraphal/nodebinary.cpp \
	../libgraphal/node.cpp \
	../libgraphal/mutexlocker.cpp \
	../libgraphal/mutex.cpp \
	../libgraphal/logger.cpp \
	../libgraphal/lexaniteratorstring.cpp \
	../libgraphal/lexaniteratorfile.cpp \
	../libgraphal/lexaniterator.cpp \
	../libgraphal/lexan.cpp \
	../libgraphal/init_static_objects.cpp \
	../libgraphal/exitvalue.cpp \
	../libgraphal/context.cpp \
	../libgraphal/codeposition.cpp \
	../libgraphal/climutex.cpp \
	../libgraphal/clilogger.cpp \
	../libgraphal/clifactory.cpp \
	../libgraphal/callstackitem.cpp \
	../libgraphal/baseobject.cpp \
	../libgraphal/generated/parser.cpp \
	../libgraphal/generated/nodeunarysub.cpp \
	../libgraphal/generated/nodeunaryreturn.cpp \
	../libgraphal/generated/nodeunarynot.cpp \
	../libgraphal/generated/nodeunaryincpre.cpp \
	../libgraphal/generated/nodeunaryincpost.cpp \
	../libgraphal/generated/nodeunarydecpre.cpp \
	../libgraphal/generated/nodeunarydecpost.cpp \
	../libgraphal/generated/nodebuiltinvisuseweightwhenpaintingedges.cpp \
	../libgraphal/generated/nodebuiltinvissetview.cpp \
	../libgraphal/generated/nodebuiltinvissetpos.cpp \
	../libgraphal/generated/nodebuiltinvissetcolor.cpp \
	../libgraphal/generated/nodebuiltinvisscreenshot.cpp \
	../libgraphal/generated/nodebuiltinvisregister.cpp \
	../libgraphal/generated/nodebuiltinvisgetgraph.cpp \
	../libgraphal/generated/nodebuiltinverify.cpp \
	../libgraphal/generated/nodebuiltinunion.cpp \
	../libgraphal/generated/nodebuiltinstruct.cpp \
	../libgraphal/generated/nodebuiltinsize.cpp \
	../libgraphal/generated/nodebuiltinsetpropertytoallvertices.cpp \
	../libgraphal/generated/nodebuiltinsetpropertytoallstructitems.cpp \
	../libgraphal/generated/nodebuiltinsetpropertytoalledges.cpp \
	../libgraphal/generated/nodebuiltinsetdirected.cpp \
	../libgraphal/generated/nodebuiltinset.cpp \
	../libgraphal/generated/nodebuiltinresetiterator.cpp \
	../libgraphal/generated/nodebuiltinremove.cpp \
	../libgraphal/generated/nodebuiltinpushfront.cpp \
	../libgraphal/generated/nodebuiltinpushback.cpp \
	../libgraphal/generated/nodebuiltinprintstacktrace.cpp \
	../libgraphal/generated/nodebuiltinprintln.cpp \
	../libgraphal/generated/nodebuiltinprint.cpp \
	../libgraphal/generated/nodebuiltinpopfront.cpp \
	../libgraphal/generated/nodebuiltinpopback.cpp \
	../libgraphal/generated/nodebuiltinnext.cpp \
	../libgraphal/generated/nodebuiltinloadfromfile.cpp \
	../libgraphal/generated/nodebuiltiniterator.cpp \
	../libgraphal/generated/nodebuiltinisvertex.cpp \
	../libgraphal/generated/nodebuiltinisstruct.cpp \
	../libgraphal/generated/nodebuiltinisstring.cpp \
	../libgraphal/generated/nodebuiltinisset.cpp \
	../libgraphal/generated/nodebuiltinisnull.cpp \
	../libgraphal/generated/nodebuiltinisint.cpp \
	../libgraphal/generated/nodebuiltinisgraph.cpp \
	../libgraphal/generated/nodebuiltinisfloat.cpp \
	../libgraphal/generated/nodebuiltinisedge.cpp \
	../libgraphal/generated/nodebuiltinisdirected.cpp \
	../libgraphal/generated/nodebuiltinisbool.cpp \
	../libgraphal/generated/nodebuiltinisarray.cpp \
	../libgraphal/generated/nodebuiltininvertedgesdirection.cpp \
	../libgraphal/generated/nodebuiltinintersection.cpp \
	../libgraphal/generated/nodebuiltininsert.cpp \
	../libgraphal/generated/nodebuiltinhasnext.cpp \
	../libgraphal/generated/nodebuiltingraph.cpp \
	../libgraphal/generated/nodebuiltingetvertices.cpp \
	../libgraphal/generated/nodebuiltingetnumvertices.cpp \
	../libgraphal/generated/nodebuiltingetnumedges.cpp \
	../libgraphal/generated/nodebuiltingetneighbors.cpp \
	../libgraphal/generated/nodebuiltingetendvertex.cpp \
	../libgraphal/generated/nodebuiltingetedges.cpp \
	../libgraphal/generated/nodebuiltingetdegree.cpp \
	../libgraphal/generated/nodebuiltingetbeginvertex.cpp \
	../libgraphal/generated/nodebuiltingetadjacencymatrix.cpp \
	../libgraphal/generated/nodebuiltingeneratevertex.cpp \
	../libgraphal/generated/nodebuiltingenerateedge.cpp \
	../libgraphal/generated/nodebuiltinfront.cpp \
	../libgraphal/generated/nodebuiltinexit.cpp \
	../libgraphal/generated/nodebuiltinecho.cpp \
	../libgraphal/generated/nodebuiltindump.cpp \
	../libgraphal/generated/nodebuiltindifference.cpp \
	../libgraphal/generated/nodebuiltindeletevertex.cpp \
	../libgraphal/generated/nodebuiltindeleteedge.cpp \
	../libgraphal/generated/nodebuiltincontains.cpp \
	../libgraphal/generated/nodebuiltinbreakpoint.cpp \
	../libgraphal/generated/nodebuiltinback.cpp \
	../libgraphal/generated/nodebuiltinassert.cpp \
	../libgraphal/generated/nodebuiltinarray.cpp \
	../libgraphal/generated/nodebuiltin_inst.cpp \
	../libgraphal/generated/nodebinarysub.cpp \
	../libgraphal/generated/nodebinaryor.cpp \
	../libgraphal/generated/nodebinaryne.cpp \
	../libgraphal/generated/nodebinarymult.cpp \
	../libgraphal/generated/nodebinarymod.cpp \
	../libgraphal/generated/nodebinarymember.cpp \
	../libgraphal/generated/nodebinarylt.cpp \
	../libgraphal/generated/nodebinaryle.cpp \
	../libgraphal/generated/nodebinaryindex.cpp \
	../libgraphal/generated/nodebinarygt.cpp \
	../libgraphal/generated/nodebinaryge.cpp \
	../libgraphal/generated/nodebinaryeq.cpp \
	../libgraphal/generated/nodebinarydiv.cpp \
	../libgraphal/generated/nodebinaryasssub.cpp \
	../libgraphal/generated/nodebinaryassref.cpp \
	../libgraphal/generated/nodebinaryassmult.cpp \
	../libgraphal/generated/nodebinaryassmod.cpp \
	../libgraphal/generated/nodebinaryassdiv.cpp \
	../libgraphal/generated/nodebinaryassadd.cpp \
	../libgraphal/generated/nodebinaryass.cpp \
	../libgraphal/generated/nodebinaryand.cpp \
	../libgraphal/generated/nodebinaryadd.cpp \
	../graphal_gui/visualizationview.cpp \
	../graphal_gui/visualizationitemdata.cpp \
	../graphal_gui/visualization.cpp \
	../graphal_gui/texteditorprogrammers.cpp \
	../graphal_gui/texteditorlines.cpp \
	../graphal_gui/texteditorhighlighter.cpp \
	../graphal_gui/texteditor.cpp \
	../graphal_gui/settings.cpp \
	../graphal_gui/scriptthread.cpp \
	../graphal_gui/mainwindow.cpp \
	../graphal_gui/main.cpp \
	../graphal_gui/guivisualizationconnector.cpp \
	../graphal_gui/guimutex.cpp \
	../graphal_gui/guilogger.cpp \
	../graphal_gui/guifactory.cpp \
	../graphal_gui/guicontext.cpp \
	../graphal_gui/dockvisualization.cpp \
	../graphal_gui/dockvariables.cpp \
	../graphal_gui/dockscriptoutput.cpp \
	../graphal_gui/dockfiles.cpp \
	../graphal_gui/dockcallstack.cpp \
	../graphal_gui/dialogsettingsvisualization.cpp \
	../graphal_gui/dialogsettingseditor.cpp \
	../graphal_gui/dialogsettings.cpp \
	../graphal_gui/dialogscriptparameters.cpp \
	../graphal_gui/dialogreplaceconfirmation.cpp \
	../graphal_gui/dialogreplace.cpp \
	../graphal_gui/dialogincludedirs.cpp \
	../graphal_gui/dialogfind.cpp
HEADERS += ../libgraphal/visualizationconnector.h \
	../libgraphal/valuevertex.h \
	../libgraphal/valuestruct.h \
	../libgraphal/valuestring.h \
	../libgraphal/valueset.h \
	../libgraphal/valuereference.h \
	../libgraphal/valuenull.h \
	../libgraphal/valueint.h \
	../libgraphal/valueidentifier.h \
	../libgraphal/valuegraph.h \
	../libgraphal/valuefloat.h \
	../libgraphal/valueedge.h \
	../libgraphal/valuebool.h \
	../libgraphal/valuearray.h \
	../libgraphal/value.h \
	../libgraphal/tests.h \
	../libgraphal/stringtable.h \
	../libgraphal/objectfactory.h \
	../libgraphal/objectcreator.h \
	../libgraphal/nodevalue.h \
	../libgraphal/nodeunary.h \
	../libgraphal/nodeposition.h \
	../libgraphal/nodeloop.h \
	../libgraphal/nodejumpcontinue.h \
	../libgraphal/nodejumpbreak.h \
	../libgraphal/nodeglobal.h \
	../libgraphal/nodefunctionscript.h \
	../libgraphal/nodefunctioncall.h \
	../libgraphal/nodefunctionbuiltin.h \
	../libgraphal/nodefunction.h \
	../libgraphal/nodeforeach.h \
	../libgraphal/nodeemptycommand.h \
	../libgraphal/nodecondition.h \
	../libgraphal/nodeblock.h \
	../libgraphal/nodebinary.h \
	../libgraphal/node.h \
	../libgraphal/mutexlocker.h \
	../libgraphal/mutex.h \
	../libgraphal/logger.h \
	../libgraphal/lexantokens.h \
	../libgraphal/lexaniteratorstring.h \
	../libgraphal/lexaniteratorfile.h \
	../libgraphal/lexaniterator.h \
	../libgraphal/lexan.h \
	../libgraphal/graphal_version.h \
	../libgraphal/general.h \
	../libgraphal/exitvalue.h \
	../libgraphal/countptr.h \
	../libgraphal/context.h \
	../libgraphal/codeposition.h \
	../libgraphal/climutex.h \
	../libgraphal/clilogger.h \
	../libgraphal/clifactory.h \
	../libgraphal/callstackitem.h \
	../libgraphal/baseobject.h \
	../libgraphal/generated/parser.h \
	../libgraphal/generated/nodeunarysub.h \
	../libgraphal/generated/nodeunaryreturn.h \
	../libgraphal/generated/nodeunarynot.h \
	../libgraphal/generated/nodeunaryincpre.h \
	../libgraphal/generated/nodeunaryincpost.h \
	../libgraphal/generated/nodeunarydecpre.h \
	../libgraphal/generated/nodeunarydecpost.h \
	../libgraphal/generated/nodebuiltinvisuseweightwhenpaintingedges.h \
	../libgraphal/generated/nodebuiltinvissetview.h \
	../libgraphal/generated/nodebuiltinvissetpos.h \
	../libgraphal/generated/nodebuiltinvissetcolor.h \
	../libgraphal/generated/nodebuiltinvisscreenshot.h \
	../libgraphal/generated/nodebuiltinvisregister.h \
	../libgraphal/generated/nodebuiltinvisgetgraph.h \
	../libgraphal/generated/nodebuiltinverify.h \
	../libgraphal/generated/nodebuiltinunion.h \
	../libgraphal/generated/nodebuiltinstruct.h \
	../libgraphal/generated/nodebuiltinsize.h \
	../libgraphal/generated/nodebuiltinsetpropertytoallvertices.h \
	../libgraphal/generated/nodebuiltinsetpropertytoallstructitems.h \
	../libgraphal/generated/nodebuiltinsetpropertytoalledges.h \
	../libgraphal/generated/nodebuiltinsetdirected.h \
	../libgraphal/generated/nodebuiltinset.h \
	../libgraphal/generated/nodebuiltinresetiterator.h \
	../libgraphal/generated/nodebuiltinremove.h \
	../libgraphal/generated/nodebuiltinpushfront.h \
	../libgraphal/generated/nodebuiltinpushback.h \
	../libgraphal/generated/nodebuiltinprintstacktrace.h \
	../libgraphal/generated/nodebuiltinprintln.h \
	../libgraphal/generated/nodebuiltinprint.h \
	../libgraphal/generated/nodebuiltinpopfront.h \
	../libgraphal/generated/nodebuiltinpopback.h \
	../libgraphal/generated/nodebuiltinnext.h \
	../libgraphal/generated/nodebuiltinloadfromfile.h \
	../libgraphal/generated/nodebuiltiniterator.h \
	../libgraphal/generated/nodebuiltinisvertex.h \
	../libgraphal/generated/nodebuiltinisstruct.h \
	../libgraphal/generated/nodebuiltinisstring.h \
	../libgraphal/generated/nodebuiltinisset.h \
	../libgraphal/generated/nodebuiltinisnull.h \
	../libgraphal/generated/nodebuiltinisint.h \
	../libgraphal/generated/nodebuiltinisgraph.h \
	../libgraphal/generated/nodebuiltinisfloat.h \
	../libgraphal/generated/nodebuiltinisedge.h \
	../libgraphal/generated/nodebuiltinisdirected.h \
	../libgraphal/generated/nodebuiltinisbool.h \
	../libgraphal/generated/nodebuiltinisarray.h \
	../libgraphal/generated/nodebuiltininvertedgesdirection.h \
	../libgraphal/generated/nodebuiltinintersection.h \
	../libgraphal/generated/nodebuiltininsert.h \
	../libgraphal/generated/nodebuiltinhasnext.h \
	../libgraphal/generated/nodebuiltingraph.h \
	../libgraphal/generated/nodebuiltingetvertices.h \
	../libgraphal/generated/nodebuiltingetnumvertices.h \
	../libgraphal/generated/nodebuiltingetnumedges.h \
	../libgraphal/generated/nodebuiltingetneighbors.h \
	../libgraphal/generated/nodebuiltingetendvertex.h \
	../libgraphal/generated/nodebuiltingetedges.h \
	../libgraphal/generated/nodebuiltingetdegree.h \
	../libgraphal/generated/nodebuiltingetbeginvertex.h \
	../libgraphal/generated/nodebuiltingetadjacencymatrix.h \
	../libgraphal/generated/nodebuiltingeneratevertex.h \
	../libgraphal/generated/nodebuiltingenerateedge.h \
	../libgraphal/generated/nodebuiltinfront.h \
	../libgraphal/generated/nodebuiltinexit.h \
	../libgraphal/generated/nodebuiltinecho.h \
	../libgraphal/generated/nodebuiltindump.h \
	../libgraphal/generated/nodebuiltindifference.h \
	../libgraphal/generated/nodebuiltindeletevertex.h \
	../libgraphal/generated/nodebuiltindeleteedge.h \
	../libgraphal/generated/nodebuiltincontains.h \
	../libgraphal/generated/nodebuiltinbreakpoint.h \
	../libgraphal/generated/nodebuiltinback.h \
	../libgraphal/generated/nodebuiltinassert.h \
	../libgraphal/generated/nodebuiltinarray.h \
	../libgraphal/generated/nodebuiltin_inst.h \
	../libgraphal/generated/nodebinarysub.h \
	../libgraphal/generated/nodebinaryor.h \
	../libgraphal/generated/nodebinaryne.h \
	../libgraphal/generated/nodebinarymult.h \
	../libgraphal/generated/nodebinarymod.h \
	../libgraphal/generated/nodebinarymember.h \
	../libgraphal/generated/nodebinarylt.h \
	../libgraphal/generated/nodebinaryle.h \
	../libgraphal/generated/nodebinaryindex.h \
	../libgraphal/generated/nodebinarygt.h \
	../libgraphal/generated/nodebinaryge.h \
	../libgraphal/generated/nodebinaryeq.h \
	../libgraphal/generated/nodebinarydiv.h \
	../libgraphal/generated/nodebinaryasssub.h \
	../libgraphal/generated/nodebinaryassref.h \
	../libgraphal/generated/nodebinaryassmult.h \
	../libgraphal/generated/nodebinaryassmod.h \
	../libgraphal/generated/nodebinaryassdiv.h \
	../libgraphal/generated/nodebinaryassadd.h \
	../libgraphal/generated/nodebinaryass.h \
	../libgraphal/generated/nodebinaryand.h \
	../libgraphal/generated/nodebinaryadd.h \
	../graphal_gui/visualizationview.h \
	../graphal_gui/visualizationitemdata.h \
	../graphal_gui/visualization.h \
	../graphal_gui/texteditorprogrammers.h \
	../graphal_gui/texteditorlines.h \
	../graphal_gui/texteditorhighlighter.h \
	../graphal_gui/texteditor.h \
	../graphal_gui/settings.h \
	../graphal_gui/scriptthread.h \
	../graphal_gui/mainwindow.h \
	../graphal_gui/guivisualizationconnector.h \
	../graphal_gui/guimutex.h \
	../graphal_gui/guilogger.h \
	../graphal_gui/guifactory.h \
	../graphal_gui/guicontext.h \
	../graphal_gui/dockvisualization.h \
	../graphal_gui/dockvariables.h \
	../graphal_gui/dockscriptoutput.h \
	../graphal_gui/dockfiles.h \
	../graphal_gui/dockcallstack.h \
	../graphal_gui/dialogsettingsvisualization.h \
	../graphal_gui/dialogsettingseditor.h \
	../graphal_gui/dialogsettings.h \
	../graphal_gui/dialogscriptparameters.h \
	../graphal_gui/dialogreplaceconfirmation.h \
	../graphal_gui/dialogreplace.h \
	../graphal_gui/dialogincludedirs.h \
	../graphal_gui/dialogfind.h
OTHER_FILES += ../libgraphal/parser.y
FORMS += ../graphal_gui/dialogsettingsvisualization.ui \
	../graphal_gui/dialogsettingseditor.ui \
	../graphal_gui/dialogscriptparameters.ui \
	../graphal_gui/dialogreplaceconfirmation.ui \
	../graphal_gui/dialogreplace.ui \
	../graphal_gui/dialogincludedirs.ui \
	../graphal_gui/dialogfind.ui
RESOURCES += ../graphal_gui/resources.qrc
INCLUDEPATH += ../libgraphal \
	../libgraphal/generated \
	../graphal_gui
CONFIG += static
RC_FILE = graphal.rc
ICON = ../graphal_gui/images/toast/toast.icns
