<?php
/*
 * Copyright 2013 Michal Turek
 *
 * This file is part of Graphal.
 * http://graphal.sourceforge.net/
 *
 * Graphal is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * Graphal is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Graphal.  If not, see <http://www.gnu.org/licenses/>.
 */


$g_title = 'Add new built-in function';
include 'p_begin.php';
?>

<p>All built-in functions are children of <em>NodeFunctionBuiltin</em> class and are generated by <em>gen_builtin.pl</em> Perl script. To define a new built-in function you have to do:</p>

<ul>
<li>Write <em>../samples/tests.txt</em> unit test</li>
<li>Write the function declaration in format <em>$funcdecl = 'funcName(arguments) : return';</em></li>
<li>Define the code for including files</li>
<li>Define the body of the built-in function</li>
<li>Call <em>genBFClass('built-in name', 'class name', number of parameters, code, includes)</em> function</li>
<li>Run <em>make builtin</em> or <em>make rebuild</em> to regenerate the classes</li>
<li>Add the newly generated files <em>classname.hpp</em> and <em>classname.cpp</em> to the projects (Code::Blocks and Qt Creator)</li>
<li>Build the application</li>
<li>Check the changes using <em>valgrind ./bbd --unit-tests ../samples/tests.txt</em></li>
<li>Commit/send me the code</li>
</ul>

<pre class="code">
$funcdecl = 'getAdjacencyMatrix(graph) : array';

$include = &lt;&lt;END_OF_CODE;
#include "valuegraph.h"
END_OF_CODE

$code = &lt;&lt;END_OF_CODE;
	ValueGraph* g = NULL;

	if((g = par[0]-&gt;toValueGraph()) != NULL)
		return g-&gt;getAdjacencyMatrix();
	else
	{
		WARN_P(_("Bad parameters type: $funcdecl"));
		return VALUENULL;
	}
END_OF_CODE

genBFClass('getAdjacencyMatrix', 'NodeBuiltinGetAdjacencyMatrix', 1, $code, $include);
</pre>

<?php
include 'p_end.php';
?>
